import { ArrowLeft, Download, MapPin, AlertCircle, CheckCircle, AlertTriangle } from 'lucide-react';
import { Button } from '../components/ui/button';
import { useGetMyResults } from '../hooks/useQueries';
import { RiskLevel } from '../backend';
import type { Screen } from '../App';

interface ResultScreenProps {
  onNavigate: (screen: Screen) => void;
}

export default function ResultScreen({ onNavigate }: ResultScreenProps) {
  const { data: result, isLoading } = useGetMyResults();

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="w-16 h-16 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto" />
          <p className="text-lg text-muted-foreground">Loading results...</p>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4">
        <div className="text-center space-y-4">
          <AlertCircle className="w-16 h-16 text-muted-foreground mx-auto" />
          <p className="text-lg text-muted-foreground">No results found</p>
          <Button onClick={() => onNavigate('home')}>Go Home</Button>
        </div>
      </div>
    );
  }

  const getRiskConfig = (level: RiskLevel) => {
    switch (level) {
      case RiskLevel.high:
        return {
          color: 'from-red-500 to-red-600',
          bgColor: 'bg-red-50',
          textColor: 'text-red-700',
          borderColor: 'border-red-200',
          icon: AlertCircle,
          label: 'High Risk',
        };
      case RiskLevel.medium:
        return {
          color: 'from-orange-500 to-orange-600',
          bgColor: 'bg-orange-50',
          textColor: 'text-orange-700',
          borderColor: 'border-orange-200',
          icon: AlertTriangle,
          label: 'Medium Risk',
        };
      case RiskLevel.low:
        return {
          color: 'from-green-500 to-green-600',
          bgColor: 'bg-green-50',
          textColor: 'text-green-700',
          borderColor: 'border-green-200',
          icon: CheckCircle,
          label: 'Low Risk',
        };
    }
  };

  const config = getRiskConfig(result.riskLevel);
  const Icon = config.icon;

  const handleDownload = () => {
    const reportContent = `
EarlyCare Health Assessment Report
===================================

Patient: ${result.submission.name}
Age: ${result.submission.age}
Date: ${new Date(Number(result.timestamp) / 1000000).toLocaleDateString()}

Risk Level: ${config.label}

Assessment Details:
- Smoking: ${result.submission.smoking ? 'Yes' : 'No'}
- Alcohol: ${result.submission.alcohol ? 'Yes' : 'No'}
- Pain: ${result.submission.pain ? 'Yes' : 'No'}
- Lump: ${result.submission.lump ? 'Yes' : 'No'}
- Weight Loss: ${result.submission.weightLoss ? 'Yes' : 'No'}

Advice:
${result.advice}

---
Generated by EarlyCare - Early Cancer Risk Detection
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `earlycare-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      <header className="bg-white shadow-sm sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4 flex items-center gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => onNavigate('home')}
            className="hover:bg-primary/10"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-2xl font-bold text-primary">Your Results</h1>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="space-y-6 animate-in slide-in-from-bottom duration-500">
          <div className={`relative overflow-hidden rounded-3xl p-8 shadow-2xl bg-gradient-to-br ${config.color}`}>
            <div className="relative z-10 text-center space-y-6">
              <div className="flex justify-center">
                <div className="w-24 h-24 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center animate-in zoom-in duration-500">
                  <Icon className="w-12 h-12 text-white" />
                </div>
              </div>
              
              <div>
                <h2 className="text-5xl font-bold text-white mb-2">
                  {config.label}
                </h2>
                <p className="text-white/90 text-lg">
                  Assessment Complete
                </p>
              </div>
            </div>
          </div>

          <div className={`rounded-2xl border-2 ${config.borderColor} ${config.bgColor} p-6`}>
            <h3 className={`text-xl font-bold ${config.textColor} mb-3 flex items-center gap-2`}>
              <Icon className="w-5 h-5" />
              Personalized Advice
            </h3>
            <p className="text-foreground leading-relaxed text-base">
              {result.advice}
            </p>
          </div>

          <div className="bg-white rounded-2xl shadow-lg p-6 space-y-4">
            <h3 className="text-xl font-bold text-foreground mb-4">Assessment Summary</h3>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Patient Name</p>
                <p className="font-medium text-foreground">{result.submission.name}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Age</p>
                <p className="font-medium text-foreground">{result.submission.age.toString()}</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Date</p>
                <p className="font-medium text-foreground">
                  {new Date(Number(result.timestamp) / 1000000).toLocaleDateString()}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Gender</p>
                <p className="font-medium text-foreground capitalize">{result.submission.gender}</p>
              </div>
            </div>

            <div className="pt-4 border-t">
              <p className="text-sm text-muted-foreground mb-3">Risk Factors</p>
              <div className="flex flex-wrap gap-2">
                {result.submission.smoking && (
                  <span className="px-3 py-1 rounded-full bg-destructive/10 text-destructive text-sm font-medium">
                    Smoking
                  </span>
                )}
                {result.submission.alcohol && (
                  <span className="px-3 py-1 rounded-full bg-destructive/10 text-destructive text-sm font-medium">
                    Alcohol
                  </span>
                )}
                {result.submission.pain && (
                  <span className="px-3 py-1 rounded-full bg-destructive/10 text-destructive text-sm font-medium">
                    Pain
                  </span>
                )}
                {result.submission.lump && (
                  <span className="px-3 py-1 rounded-full bg-destructive/10 text-destructive text-sm font-medium">
                    Lump
                  </span>
                )}
                {result.submission.weightLoss && (
                  <span className="px-3 py-1 rounded-full bg-destructive/10 text-destructive text-sm font-medium">
                    Weight Loss
                  </span>
                )}
                {!result.submission.smoking && !result.submission.alcohol && !result.submission.pain && 
                 !result.submission.lump && !result.submission.weightLoss && (
                  <span className="px-3 py-1 rounded-full bg-green-100 text-green-700 text-sm font-medium">
                    No risk factors reported
                  </span>
                )}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Button
              size="lg"
              className="h-14 text-base"
              onClick={() => window.open('https://www.google.com/maps/search/hospitals+near+me', '_blank')}
            >
              <MapPin className="w-5 h-5 mr-2" />
              Find Hospital
            </Button>
            
            <Button
              size="lg"
              variant="outline"
              className="h-14 text-base"
              onClick={handleDownload}
            >
              <Download className="w-5 h-5 mr-2" />
              Download Report
            </Button>
          </div>

          <Button
            variant="ghost"
            className="w-full h-12 text-base"
            onClick={() => onNavigate('home')}
          >
            Back to Home
          </Button>
        </div>
      </main>
    </div>
  );
}
